---
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
- name: Restart Traffic Ops
  systemd:
    name: traffic_ops
    state: restarted
    daemon_reload: yes
  notify: Wait for Traffic Ops Golang to become available

- name: Wait for Traffic Ops Golang to become available
  wait_for:
    delay: 3
    port: "{{ to_go_port }}"
  notify: Wait for Traffic Ops Perl to become available

- name: Wait for Traffic Ops Perl to become available
  wait_for:
    delay: 3
    port: "{{ to_hypnotoad_port }}"
