---
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
- name: Get a copy of the tomcat pid
  shell: ps aux | grep tomcat | grep -v grep | tr -s ' ' | cut -d' ' -f2
  register: tr_old_tomcat_pid

- name: Stop Tomcat6
  block:
  - name: Ask Tomcat6 to kindly stop
    service:
      name: tomcat
      state: stopped

  - name: Ensure Tomcat actually stops
    wait_for:
      path: "/proc/{{tr_old_tomcat_pid.stdout}}"
      state: absent
      delay: 5
      timeout: 60

  rescue:
    - name: Force Tomcat to die
      shell: "kill -9 {{tr_old_tomcat_pid.stdout}}"
  become: yes

- name: Remove old traffic_router
  yum:
    name: traffic_router
    state: absent
    lock_timeout: 300
    enablerepo: "{{ additional_yum_repos | default([]) }}"
  become: yes
  retries: 5
  delay: 5

- name: Purge old configs
  file:
    name: "{{item}}"
    state: absent
  with_items:
    - /opt/tomcat/bin/setenv.sh
    - /etc/init.d/tomcat
    - /etc/systemd/system/tomcat.service
    - /opt/traffic_router/conf/http.properties
  become: yes
